language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: curso-github-cefire-bsm
  on: master
  skip_cleanup: true
  api_key:
    secure: aTxoUL2WF2bUPoWjYf1SNyQo7rPGPO5fddmbWCP+Y6ow2zPyvDfoBQbQynPKBSNnYv7H5cVPpNiQC9tTBoLZxRKds+s8ErHd/tzK425Vzsj3nENTrml/BILDmp2egCefilPAS69Rga2dXIKIwrLTHwUlIXuGkvMASqpybVASmdeqc/6wQj8gYPTedIV57mMbNApLeQkj/7N5hcEGvlLPE6GojcciOwDNZjxKppuYWN+E36UY4SMtmUApaSIIQ6iI/WqrrhXPyyYSyhOSzmlby9IVR2jIIIHvKqQTpLfNlWcMGaGZRFL3dBIOqjf84WtG52ulcN7P9CugE4yw/FmWamo0WsZPdvtpoKtS6CKh/Bn8knWTDT3ky1IkW/R78W1yChw0ripk9Dbh5/VzBjiDxtTrkJFB1qCFSIZA/uWFuCWGSSR+xURC4ma7T1SttKMY0xLPVqyOVGJOPX0Hes8jX46aRDELY4X+L0pXTmaR81R5i6EimqU6B/FkVvu3RmG1hQaYPoAvAdVyvc4ZWAc60hYuV/lp8y/XhjKLm8m2NGkm0Bk9nJe248m41VaKWn736pyUoddt7mWIV+SpsQEtoD7nuyeQkQoJBUH4Jw0OHHW21VIHFKfDWPDV6ZKFhavICCh/BDZh+G9eZ0Wv3GqB90LPeHwFbgmsyduJ47cHuY4=
